apiVersion: v1
kind: ConfigMap
data:
  rfbpaApi: "{{ .Values.host }}/api/public"
  authUrl: {{ quote .Values.auth.authUrl }}
  authClient: {{ quote .Values.auth.jwtClient }}
metadata:
  name: {{ include "rfbpa.webApp.name" . }}
  labels:
    component: rest-api
    app.kubernetes.io/component: rest-api
    app.kubernetes.io/name: {{ include "rfbpa.restApi.name" . }}
    {{- include "rfbpa.labels" . | nindent 4 }}
