apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "rfbpa.webApp.name" . }}
  labels:
    component: web-app
    app.kubernetes.io/component: web-app
    {{- include "rfbpa.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  revisionHistoryLimit: 2
  selector:
    matchLabels:
      {{- include "rfbpa.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "rfbpa.labels" . | nindent 8 }}
    spec:
      containers:
        - name: {{ .Chart.Name }}
          image: {{ quote .Values.webApp.image }}
          imagePullPolicy: Always
          env:
            - name: RFBPA_ENVIRONMENT
              value: production
            - name: RFBPA_AUTH_JWKS_ENDPOINT
              valueFrom:
                configMapKeyRef:
                  name: {{ include "rfbpa.rest-api.name" . }}
                  key: jwksEndpoint
            - name: RFBPA_JWT_ISSUER
              valueFrom:
                configMapKeyRef:
                  name: {{ include "rfbpa.rest-api.name" . }}
                  key: jwtIssuer
            - name: RFBPA_JWT_REALM
              valueFrom:
                configMapKeyRef:
                  name: {{ include "rfbpa.rest-api.name" . }}
                  key: jwtRealm
          ports:
            - name: {{ include "rfbpa.webApp.name" . }}
              containerPort: 80
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /health
              port: {{ include "rfbpa.webApp.name" . }}
          readinessProbe:
            httpGet:
              path: /health
              port: {{ include "rfbpa.webApp.name" . }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
