apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "rfbpa.fullname" . }}
  labels:
    {{- include "rfbpa.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  revisionHistoryLimit: 2
  selector:
    matchLabels:
      {{- include "rfbpa.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "rfbpa.labels" . | nindent 8 }}
        revision: "6"
    spec:
      containers:
        - name: {{ .Chart.Name }}
          image: {{ quote .Values.image }}
          imagePullPolicy: Always
          env:
            - name: RFBPA_AXP_USER
              value: "rohdef"
            - name: RFBPA_AXP_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ include "rfbpa.fullname" . }}
                  key: axpPassword
            - name: RFBPA_ENVIRONMENT
              value: production
            - name: RFBPA_AUTH_JWKS_ENDPOINT
              valueFrom:
                configMapKeyRef:
                  name: {{ include "rfbpa.fullname" . }}
                  key: jwksEndpoint
            - name: RFBPA_JWT_ISSUER
              valueFrom:
                configMapKeyRef:
                  name: {{ include "rfbpa.fullname" . }}
                  key: jwtIssuer
            - name: RFBPA_JWT_REALM
              valueFrom:
                configMapKeyRef:
                  name: {{ include "rfbpa.fullname" . }}
                  key: jwtRealm
          volumeMounts:
            - mountPath: /helpers.yaml
              name: rfbpa-temp
              subPath: helpers.yaml
          ports:
            - name: rfbpa-web
              containerPort: 8080
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /health
              port: 8080
          readinessProbe:
            httpGet:
              path: /health
              port: 8080
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      volumes:
        - name: rfbpa-temp
          configMap:
            defaultMode: 420
            name: rbpa-temp-config
