apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/namespace-wide: "true"
  labels:
    component: rest-api
    app.kubernetes.io/component: rest-api
    {{- include "rfbpa.labels" . | nindent 4 }}
  name: {{ include "rfbpa.rest-api.name" . }}
spec:
  encryptedData:
    axpPassword: "AgBuhWk0tm7PwvX9svkRW/9w9aar7POypVb2s9uAdFH6rEXsqW/9MbFQoTIHJqiN1xqoZSyiLV9Y51AKhI8OHmGa4Z1zEp5kTRudJy3TyDZU6pHw7f9ljgtHVYLE/fEXr2JlCJ+ebkDPOfhpl349T8GZtICFdRnyJyalsbRomse9jxnZ7VwA7gZCmifXj4gaL4u5Ipt+S8FsQ99oTS3JgaoO5+empP/8ExSNnuw/L6CVxz+PxgEHQTQo6iut+egqBx6hDFfX/V2ZU/vYvYKv504YGUqiJColABYe8Mh9n49CsuusQ2n+n2F09oXj/HGXrK0mTYOCTBhIwuHHyz4VovMmhdCLjSDQyyliX1Z/nd9xEKb0Ss0GksboQqCibOVOSbZzt+XrLt1fCDWervKKqUJt4fm6qwvYQ6VrHGW7zk/Rq+Lgl8f0WR9/iN2mSIYBw88tLE6WD37hYJeNelTy8HGmxwjwRVyIiFwuuqeHLFjdmqxeV+N9U1pBREfFWiKsNhbHWXzdyn16p58QgjuiGXCdmqo+XKO3Shy5A8DYtMM6o0w69hAyc7xGFbNdpb7wpVzchvhSnZTY0eMaVhtOD6hbav+4ZgbE3cSGCwKUWbVBpBNmAIWS+P/gsZgihbjP6Ag4AuD+EIPn5vBLs7a26sybqERuSbOnvCIQRqIGhfubb8+HudlG50/ayBkiCPIy+Hz5QrTm3d3xtpwDPAQD3A=="
  template:
    type: Opaque
    metadata:
      annotations:
        sealedsecrets.bitnami.com/namespace-wide: "true"
      labels:
        component: rest-api
        app.kubernetes.io/component: rest-api
        app.kubernetes.io/name: {{ include "rfbpa.rest-api.name" . }}
        {{- include "rfbpa.selectorLabels" . | nindent 8 }}
