apiVersion: v1
kind: Service
metadata:
  name: {{ include "rfbpa.restApi.name" . }}
  labels:
    component: rest-api
    app.kubernetes.io/component: rest-api
    {{- include "rfbpa.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  ports:
    - port: 80
      targetPort: {{ include "rfbpa.restApi.name" . }}
      protocol: TCP
      name: http
  selector:
    {{- include "rfbpa.selectorLabels" . | nindent 4 }}
