apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "rfbpa.fullname" . }}
  labels:
    {{- include "rfbpa.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  revisionHistoryLimit: 2
  selector:
    matchLabels:
      {{- include "rfbpa.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "rfbpa.labels" . | nindent 8 }}
        revision: "6"
    spec:
      containers:
        - name: {{ .Chart.Name }}
          image: {{ quote .Values.image }}
          imagePullPolicy: Always
          ports:
            - name: rfbpa-web
              containerPort: 8080
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /health
              port: 8080
          readinessProbe:
            httpGet:
              path: /health
              port: 8080
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
