apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "rfbpa.restApi.name" . }}
  labels:
    {{- include "rfbpa.labels" . | nindent 4 }}
  annotations:
    component: rfbpa
    app.kubernetes.io/component: rfbpa
    kubernetes.io/ingress.class: nginx
    kubernetes.io/tls-acme: "true"
    cert-manager.io/cluster-issuer: letsencrypt-production
spec:
  ingressClassName: nginx
  rules:
     - host: rfbpa.rohdef.dk
       http:
         paths:
           - path: /api/public
             pathType: Prefix
             backend:
               service:
                 name: {{ include "rfbpa.restApi.name" . }}
                 port: {{ include "rfbpa.restApi.name" . }}-service
           - path: /
             pathType: Prefix
             backend:
               service:
                 name: {{ include "rfbpa.webApp.name" . }}
                 port: {{ include "rfbpa.webApp.name" . }}-service
  tls:
    - hosts:
        - rfbpa.rohdef.dk
      secretName: rfbpa-ingress-cert
