replicaCount: 1

image:
  repository: ghcr.io/rohdef/rf-bpa
  tag: latest

imagePullSecrets: []

livenessProbe:
  httpGet:
    path: /
    port: http
readinessProbe:
  httpGet:
    path: /
    port: http
