replicaCount: 1

host: rfbpa.rohdef.dk

webApp:
  image: ghcr.io/rohdef/rfbpa-web-app:latest

restApi:
  image: ghcr.io/rohdef/rfbpa-rest-api:latest

auth:
  jwksEndpoint: "https://keycloak.rfbpa.rohdef.dk/realms/rfbpa/protocol/openid-connect/certs"
  authUrl: "https://keycloak.rfbpa.rohdef.dk/realms/rfbpa/protocol/openid-connect/auth"
  jwtIssuer: "https://keycloak.rfbpa.rohdef.dk/realms/rfbpa"
  jwtRealm: rfbpa
  jwtClient: rfbpa-web
