rfbpa:
  environment: "$RFBPA_ENVIRONMENT:development"

  auth:
    jwkEndpoint: "$RFBPA_AUTH_JWKS_ENDPOINT:http://localhost:8383/realms/rfbpa/protocol/openid-connect/certs"
    jwtIssuer: "$RFBPA_JWT_ISSUER:http://localhost:8383/realms/rfbpa"
    jwtRealm: "$RFBPA_JWT_REALM:rfbpa"

  axp:
    host: "$RFBPA_AXP_HOST:https://www.handicapformidlingen.axp.dk"
    username: $RFBPA_AXP_USER
    password: $RFBPA_AXP_PASSWORD

ktor:
  development: true
  deployment:
    watch:
      - classes
      - resources
    port: 8080
  application:
    modules:
      - dk.rohdef.rfbpa.web.MainKt.main
