name: Build container
description: ""

inputs:
  input-path:
    description: Path to build docker image from
    default: "."
    required: true
  image-destination-host:
    description: "Where to upload the artifact to - if only local is desired just use \"localhost:5000\" - trailing slash is not allowed"
    default: ghcr.io
    required: true
  image-destination-name:
    description: "The desired name of the output artifact, defaults to: \"owner/repository\""
    default: "${{ github.repository }}"
    required: false
#  image-destination-tag-override:
#    description: "If the default tag generation is to be overridden"
#    default: ""
#    required: false


outputs:
  container-image:
    description: The random image name used for generation
    value: ${{ steps.build-image.outputs.container-image }}
  image-digest:
    description: The digest of the final image
    value: ${{ steps.push-image.outputs.image-digest }}

runs:
  using: composite
  steps:
    - name: Build docker container
      id: build-container
      uses: rohdef/action-build-scan-push-container@main
      with:
        dockerfile-path: "${{ inputs.input-path  }}"
        labels: |
          org.opencontainers.image.authors=Rohde Fischer (rohdef@rohdef.dk)
          org.opencontainers.image.vendor=Rohde Fischer
          org.opencontainers.image.ref.name=rfbpa-1
          org.opencontainers.image.title=rfbpa - A BPA manager
          org.opencontainers.image.description=A BPA administration tool for usage with AXP used by Handicapformidlingen
