name: Building and distributing rfbpa
run-name: rfbpa - ${{ github.actor }} on ${{ github.ref }}
on: [ push ]

env:
  REST_API_IMAGE_NAME: rfbpa-rest-api
  WEB_APP_IMAGE_NAME: rfbpa-web-app

jobs:
  code-scan:
    permissions:
      contents: read
      security-events: write
    runs-on: ubuntu-latest
    steps:
      - name: "Check out repository: ${{ github.repository }}"
        uses: actions/checkout@v4

      - name: Scan code for vulnerabilities
        uses: aquasecurity/trivy-action@0.28.0
        with:
          scan-type: "fs"
          format: "sarif"
          output: "code-scan-results.sarif"

      - name: Upload code scan to Security tab
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: 'code-scan-results.sarif'
          category: code-scan

  web-app:
    permissions:
      contents: read
      packages: write
    runs-on: ubuntu-latest
    outputs:
      docker_digest: ${{ steps.push_image.outputs.docker_digest }}
    steps:
      - name: "Check out repository: ${{ github.repository }}"
        uses: actions/checkout@v4
      - name: Set up NodeJS
        uses: actions/setup-node@v4
        with:
          node-version: '18'

      - name: Build web-app
        run: |
          cd web-app
          npm ci
          npm run build

      - name: Log in to docker registry
        run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin

      - name: Build and push container
        id: build-container
        uses: ./.github/actions/build-container
        with:
          input-path: ./web-app/
          image-destination-name: ${{ github.repository_owner }}/$WEB_APP_IMAGE_NAME

  rest-api:
    permissions:
      contents: read
      packages: write
      security-events: write
    runs-on: ubuntu-latest
    outputs:
      docker_digest: ${{ steps.push_image.outputs.docker_digest }}
    steps:
      - name: "Check out repository: ${{ github.repository }}"
        uses: actions/checkout@v4

      - name: Set up Java
        uses: actions/setup-java@v4
        with:
          java-version: 23
          distribution: "temurin"
          cache: gradle

      - name: Build rest-api
        run: |
          ./gradlew build

      - name: Log in to docker registry
        run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin

      - name: Build and push container
        id: build-container
        uses: ./.github/actions/build-container
        with:
          input-path: ./rest-api/
          image-destination-name: ${{ github.repository_owner }}/$REST_API_IMAGE_NAME


  deployment:
    needs:
      - rest-api
      - web-app
    permissions:
      contents: read
      packages: write
    runs-on: ubuntu-latest
    env:
      REST_API_DIGEST: ${{ needs.rest-api.outputs.image-digest }}
      WEB_APP_DIGIEST: ${{ needs.web-app.outputs.docker_digest }}
    steps:
      - name: "Check out repository: ${{ github.repository }}"
        uses: actions/checkout@v4
        with:
          path: rfbpa
      - name: Check out gitops repository
        uses: actions/checkout@v4
        with:
          path: rfbpa-deploy
          repository: rohdef/rfbpa-deploy
          ssh-key: ${{ secrets.RFBPA_DEPLOY_SSH_KEY }}
      - name: Update deployment
        run: |
          rm -rf ./rfbpa-deploy/rfbpa
          cp -r ./rfbpa/deployment/ ./rfbpa-deploy/rfbpa
          yq e -i ".restApi.image=\"${REST_API_DIGEST}\"" ./rfbpa-deploy/rfbpa/values.yaml
          yq e -i ".webApp.image=\"${WEB_APP_DIGIEST}\"" ./rfbpa-deploy/rfbpa/values.yaml
          cd rfbpa-deploy
          git config user.email "rohdef+rfbpa@rohdef.dk"
          git config user.name "${{ github.actor }}"
          git add .
          git commit --allow-empty -m "Updating deployment"
          git push
