name: Test action
on:
  push: {}
  workflow_dispatch: {}

jobs:
  test-it:
    runs-on: ubuntu-latest
    steps:
      - name: "Check out repository: ${{ github.repository }}"
        uses: actions/checkout@v4

      - name: Set up Java
        uses: actions/setup-java@v4
        with:
          java-version: 23
          distribution: "temurin"
          cache: gradle

      - name: Build rest-api
        run: |
          ./gradlew build

      - name: Run my action
        id: build-container
        uses: rohdef/action-build-scan-push-container@main
        with:
          dockerfile-path: ./rest-api/
          labels: |
            org.opencontainers.image.authors=Rohde Fischer (rohdef@rohdef.dk)
            org.opencontainers.image.vendor=Rohde Fischer
            org.opencontainers.image.ref.name=rfbap-1
            org.opencontainers.image.title=rfbpa - A BPA manager
            org.opencontainers.image.description=A BPA administration tool for usage with AXP used by Handicapformidlingen
          build-args: |
            version=awesome-500
            secondary=hmm

      - name: Finish
        run: |
          echo "Be done"
          echo ${{ steps.build-container.outputs.imageid }}
          echo ${{ steps.build-container.outputs.digest }}
